Repository OpenDRR/boundaries, pull requests merged in 2021-07, with the labels that each got.

#21 gpkg-to-pgdump: Upload to Amazon S3 bucket too
  .github/workflows/gpkg-to-pgdump.yml
Labels: Priority: Should Have, Requirement

#23 Update hexbins v1p1
  Geometry_CANADA.gpkg
  Geometry_CDUID.gpkg
  README.md
  hexbin_4326/SAUID_HexGrid.gpkg
  hexbin_4326/SAUID_HexGrid_100km_intersect.gpkg
  hexbin_4326/SAUID_HexGrid_10km_intersect.gpkg
  hexbin_4326/SAUID_HexGrid_25km_intersect.gpkg
  hexbin_4326/SAUID_HexGrid_50km_intersect.gpkg
  hexbin_4326/SAUID_HexGrid_5km_intersect.gpkg
  opendrr-boundaries.sql
Labels: Bug, Enhancement, Task

#24 Upload as artifact and release assets on GitHub
  .github/workflows/gpkg-to-pgdump.yml
Labels: Enhancement
